#!/bin/bash

#
# Notes:
# - to list the keystore contents:
#     keytool -list -v -keystore mbs2.keystore
#

if [ -e mbs2.keystore ]; then
  echo "*** ERROR mbs2.keystore exists ***"
  exit 1
fi

keytool -genkey -v -keystore mbs2.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias mbs2

